# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone (e.g., America/New_York)
timezone: UTC

# jekyll-seo-tag settings
title: Wael Rdifi
tagline: N0 Syst3m 1s Saf2
description: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
url: https://wael-rd.github.io

github:
  username: Wael-Rd

twitter:
  username: wael46757112

social:
  name: Wael Rdifi
  email: tm6.rdifi100@gmail.com
  links:
    - https://github.com/Wael-Rd
    - https://www.linkedin.com/in/wael-rd
    - https://x.com/wael46757112

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  provider: false # Set to false if no analytics provider is used
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider: false # Set to false if not using GoatCounter

# Prefer color scheme setting
theme_mode: dark # [light | dark]

# The CDN endpoint for media resources
cdn:

# Sidebar avatar
avatar: https://avatars.githubusercontent.com/u/126264620?s=400&u=d35eb68bc19cb80a917d53ede0cc62c843180c83&v=4

# Site-wide social preview image
social_preview_image:

# Global switch for TOC in posts
toc: true

# Comments settings
comments:
  provider: # Leave empty to disable comments
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: en
    reactions_enabled: 1

# Self-hosted static assets
assets:
  self_host:
    enabled: false
    env:

# PWA settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# Pagination
paginate: 10

# The base URL of your site
baseurl: ""

# Kramdown settings
kramdown:
  footnote_backlink: "↩︎"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Sass
sass:
  style: compressed

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Exclude files
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

# Jekyll archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
